import Head from "next/head";
import dynamic from "next/dynamic";

import { RootState } from "@/app/store";
import { useAppSelector } from "@/app/hooks";
import ChordName from "@/components/ChordName";

export default function Home() {
  const singleData = useAppSelector(
    (state: RootState) => state.searchDataSlice.singleData
  );

  const DynamicComponentWithNoSSR = dynamic(
    () => import("../components/Guitar"),
    { ssr: false }
  );

  console.log(singleData, "data");

  return (
    <>
      <Head>
        <title>Chordy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="w-full overflow-hidden bg-black h-full">
          <DynamicComponentWithNoSSR
            id={singleData?.[0]?.id}
            data={singleData?.[0]}
          />
        </div>
        <ChordName />
      </main>
    </>
  );
}
